# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=first.models.upload_cv)),
                ('notes', models.CharField(max_length=1024)),
            ],
        ),
    ]
