# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
