# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20170902_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
